// Editorial source for the atlas. Only the rendered article is deployed.
export const sources = {
 architecture: ['Hopper architecture', 'https://developer.nvidia.com/blog/nvidia-hopper-architecture-in-depth/'],
 specs: ['H100 product specifications', 'https://www.nvidia.com/en-us/data-center/h100/'],
 whitepaper: ['Hopper architecture whitepaper', 'https://resources.nvidia.com/en-us-hopper-architecture/nvidia-h100-tensor-c'],
 tuning: ['Hopper tuning guide', 'https://docs.nvidia.com/cuda/hopper-tuning-guide/index.html'],
 cuda: ['CUDA programming guide', 'https://docs.nvidia.com/cuda/cuda-programming-guide/index.html'],
 practices: ['CUDA best practices', 'https://docs.nvidia.com/cuda/cuda-c-best-practices-guide/index.html'],
 ptx: ['PTX instruction reference', 'https://docs.nvidia.com/cuda/parallel-thread-execution/index.html'],
 packaging: ['TSMC CoWoS packaging', 'https://www.tsmc.com/english/dedicatedFoundry/technology/cowos'],
 fp8: ['FP8 formats paper', 'https://arxiv.org/abs/2209.05433'],
 scaling: ['Transformer Engine: FP8 scaling', 'https://docs.nvidia.com/deeplearning/transformer-engine-releases/release-1.6/user-guide/examples/fp8_primer.html'],
 dpx: ['NVIDIA: dynamic programming and DPX', 'https://blogs.nvidia.com/blog/nvidia-hopper-accelerates-dynamic-programming-using-dpx-instructions/'],
 mig: ['Multi-Instance GPU guide', 'https://docs.nvidia.com/datacenter/tesla/mig-user-guide/introduction.html'],
 security: ['H100 confidential computing', 'https://developer.nvidia.com/blog/confidential-computing-on-h100-gpus-for-secure-and-trustworthy-ai/'],
 ecc: ['GPU memory error management', 'https://docs.nvidia.com/deploy/pdf/NVIDIA-GPU-Memory-Error-Management.pdf'],
 fabric: ['NVSwitch fabric manager guide', 'https://docs.nvidia.com/datacenter/tesla/fabric-manager-user-guide/'],
 profile: ['Nsight Compute profiling guide', 'https://docs.nvidia.com/nsight-compute/ProfilingGuide/'],
 dgx: ['DGX H100 system guide', 'https://docs.nvidia.com/dgx/dgxh100-user-guide/'],
 cutlass: ['NVIDIA CUTLASS: Hopper GEMM example', 'https://github.com/NVIDIA/cutlass/blob/main/examples/cute/tutorial/hopper/wgmma_tma_sm90.cu']
};
// id, scale, system, title, specification, explanation, connection, limitation, sources.
export const parts = [
['board','package','structure','SXM module','The board around the package',
'The green board is a carrier. It routes power and high-speed signals between the GPU package, voltage regulators, and the server’s baseboard. The GPU die is only the small piece of silicon at its center. SXM names a module form factor; it does not mean a PCIe graphics card with a different heatsink.',
'Trace the stack upward: module → package substrate → interposer → GPU and memory. Each level solves a different wiring problem.',
'Board outline, component placement, routing, and component counts here are illustrative. This is not an SXM engineering drawing.',['dgx']],
['connector','package','io','Baseboard connections','Power and signals leave the module here',
'The module mates with a server baseboard. Its contacts carry power and communication signals, including paths used by PCIe and NVLink. The baseboard then connects the accelerator to the rest of the machine. An SXM module is not plugged into a desktop’s PCIe expansion slot.',
'PCIe and NVLink are different protocols even when their physical routes pass through the same module assembly.',
'The gold contacts show a connection concept, not a pinout. No pin assignments or connector dimensions are asserted.',['dgx']],
['vrm','package','power','Voltage regulators','Convert supply power into local rails',
'The GPU needs tightly controlled voltages while its current demand changes rapidly. Switching regulators, inductors, and control circuitry convert the incoming supply into the rails used by the silicon. Their conversion losses become heat too. Supplying enough average watts is insufficient if voltage droops during a sudden burst of work.',
'The regulators feed the package through conductive planes and many connections; nearby capacitors help with faster changes.',
'The blocks represent regulator stages collectively. Rail voltages, phase counts, and the exact H100 module bill of materials are not modeled.',['dgx']],
['capacitors','package','power','Decoupling capacitors','A nearby reserve of charge',
'A capacitor stores charge. Placed close to a load, it can supply brief current changes before a more distant power source responds. Many capacitors and the wiring between them form a power distribution network with frequency-dependent behavior. The goal is to keep supply voltage within limits as switching activity changes.',
'Capacitors, package connections, and voltage regulators work together. None performs the matrix multiplication, but the arithmetic depends on a stable supply.',
'These repeated pieces are representative, not an inventory of the capacitors on a particular board.',['packaging']],
['substrate','package','structure','Package substrate','Fan out dense connections',
'The package substrate sits between the fine wiring near the chips and the larger connections to the module. It provides mechanical support and routes signals and power across multiple layers. “The chip” in a product photograph often includes this package, not just the bare GPU die.',
'The interposer handles especially dense connections between adjacent dies; the substrate carries those connections toward the board.',
'Layer thicknesses and internal copper routing are omitted. This is a conceptual package stack.',['packaging']],
['interposer','package','structure','Silicon interposer','Short, wide paths to HBM',
'An interposer lets the logic die and stacked memory sit side by side with very dense wiring between them. This is the central idea of a 2.5D assembly: several dies share an interconnect platform instead of talking only through long board traces. Short connections make a very wide memory interface practical.',
'HBM is close to the GPU, but it remains separate DRAM. The interposer is a connection layer, not an extra bank of GPU arithmetic units.',
'The model explains silicon-interposer packaging. It does not reproduce proprietary routing or a verified H100 package cross-section.',['packaging']],
['bumps','package','structure','Bumps and vertical connections','Cross the gaps between layers',
'Tiny conductive joints connect dies to their supporting interconnect layers. Through-silicon vias, or TSVs, carry connections vertically through silicon where needed, including in stacked memory. These solve different parts of the three-dimensional wiring problem: across an interface and through a die.',
'The horizontal interposer wiring and vertical connections together complete a path from memory to logic and from the package to the board.',
'The visible dots are magnified symbols. Their number, pitch, and arrangement are not the physical H100 connection map.',['packaging']],
['die','package','compute','GH100 logic die','80 billion transistors · 814 mm²',
'This is the silicon containing the GPU’s compute units, on-chip caches, control logic, and interfaces. GH100 is the die design; H100 is the product built around it. NVIDIA uses a customized TSMC 4N process. A process name describes a manufacturing generation, not a claim that every transistor dimension is four nanometers.',
'Open the GPU view to separate the die into functional blocks. Memory stacks alongside it are separate pieces of silicon.',
'The die surface is an original schematic texture, not a die photograph or recovered transistor layout.',['architecture']],
['hbm','package','memory','HBM3 memory stacks','80 GB across five active stacks',
'HBM means high-bandwidth memory. DRAM dies are stacked vertically, then placed beside the GPU. A very wide interface allows many bits to move in parallel. This is where model weights, activations, and other large allocations usually live while the GPU works.',
'The five active stacks connect through ten 512-bit memory controllers: a 5,120-bit interface in total. HBM feeds caches and compute; it does not execute Tensor Core instructions.',
'This model shows five active stacks. The full GH100 design supports six; stack placement and the number of visible DRAM layers here are schematic.',['architecture']],
['cooler','package','power','Thermal interface and cooler','Up to 700 W module TDP',
'Heat must leave the silicon through an interface material and a cooling assembly. Thermal interface material fills microscopic gaps; a heatsink or cold plate moves heat toward air or liquid. The server’s cooling system must then carry that heat away. A high power limit is only useful if temperatures remain controlled.',
'Clocks, voltage, workload, power limits, and temperature jointly affect sustained performance. A peak specification does not promise an indefinitely sustained operating point.',
'The removable finned assembly is a generic cooling illustration, not a specified H100 cooler. TDP is not a measurement of every workload’s draw.',['specs','dgx']],
['gpc','gpu','compute','GPU processing clusters','Eight GPCs',
'A GPC groups lower-level processing resources. It is one level in the GPU’s hierarchy, above texture processing clusters and streaming multiprocessors. Understanding the hierarchy helps distinguish a whole device from the execution resources that a kernel actually occupies.',
'The GPU view uses eight outlined regions. Each small green compute tile represents a pair of SMs, called a TPC.',
'This is a functional arrangement, not a measured silicon floorplan. The distribution of enabled tiles across regions is illustrative.',['architecture']],
['tpc','gpu','compute','Texture processing clusters','66 enabled TPCs · two SMs each',
'The TPC name comes from graphics history. In this H100 configuration, 66 enabled TPCs account for 132 SMs. The complete GH100 design has 72 TPCs and 144 SMs. A product can expose fewer resources than the full design; the full diagram and the shipping specification describe different things.',
'Open one SM to see the arithmetic, storage, and scheduling resources repeated inside those tiles.',
'The disabled locations on a particular chip are not public here. No individual tile in this atlas is claimed to correspond to a known fused-off location.',['architecture']],
['l2','gpu','memory','L2 cache','50 MB shared on-chip cache',
'L2 is a cache between the SMs and off-chip memory. Reusing a value from L2 can avoid another trip to HBM. But fitting a tensor in HBM says nothing about fitting it in L2: these capacities differ by orders of magnitude.',
'An SM’s load can be satisfied nearer the computation if the data is already cached. Otherwise the request proceeds toward the memory controllers and HBM.',
'Cache hit rate depends on the access pattern and competing traffic. The gold strips are a logical grouping, not exact cache-bank geometry.',['tuning']],
['fabric','gpu','io','On-chip interconnect','Routes requests and responses',
'Compute units, caches, memory controllers, and external interfaces need a communication network inside the die. The interconnect routes their traffic. Moving a value has a cost in bandwidth, latency, and energy even when both endpoints are on the same chip.',
'MIG can assign distinct paths and cache resources to separate GPU instances. A full-size job and a partitioned job therefore see different available resources.',
'The lines illustrate connectivity, not a published wire map or a measured internal bandwidth.',['mig']],
['controller','gpu','memory','Memory controllers and PHYs','Ten active 512-bit controllers',
'Controllers turn memory requests into operations that the DRAM can perform. Physical interfaces, or PHYs, handle the electrical signaling. A wide interface helps throughput, but accesses still face scheduling, timing, and contention. Peak bandwidth is easier to approach with enough well-organized traffic.',
'Coalesced requests and reuse reduce unnecessary memory work. Random small reads are a different workload from a long contiguous transfer.',
'The count is for H100 SXM; drawn controller sizes and locations are schematic.',['architecture','practices']],
['nvlink','gpu','io','NVLink interfaces','18 links · 900 GB/s bidirectional total',
'NVLink connects GPUs through a high-bandwidth fabric. The advertised aggregate adds both directions: 900 GB/s total corresponds to 450 GB/s in each direction across the links. It is not 900 GB/s of local HBM bandwidth, and it does not turn every other GPU’s memory into equally fast local memory.',
'NVSwitch can connect these links outside the GPU. Algorithms still need to partition work and communicate results.',
'Topology and software determine useful application bandwidth. NVSwitch is external and is not a block inside GH100.',['tuning','fabric']],
['pcie','gpu','io','PCIe host interface','Gen 5 ×16',
'PCIe provides a path to the host system and other devices. NVIDIA quotes roughly 128 GB/s with both directions added, or roughly 64 GB/s per direction. Protocol overhead and the actual system reduce useful payload throughput. The CPU typically launches work while the GPU executes kernels on data in device memory.',
'Loading a model from storage involves more than this link: storage, host memory, the driver, and allocation all participate.',
'An SXM H100 still has a PCIe interface. SXM is a form factor, not an alternative instruction set.',['architecture']],
['copy','gpu','io','Copy engines','Move bytes while compute can proceed',
'Dedicated transfer engines support memory-copy work without spending the same arithmetic resources on every byte. Asynchronous copies can overlap computation when memory, streams, dependencies, and the hardware permit it. Merely using an asynchronous API is not proof that two operations overlap.',
'A host-to-device copy engine and the SM’s Tensor Memory Accelerator serve different scopes. TMA specializes in tensor transfers involving shared memory.',
'The illustrated block groups copy functionality; no engine count or precise physical placement is asserted.',['cuda','practices']],
['dispatch','gpu','compute','Work distribution','From a kernel grid to resident blocks',
'A CUDA kernel launches a grid of thread blocks. The device schedules blocks onto SMs where resources are available. Blocks need registers, shared memory, and thread capacity; those demands constrain how much work can reside at once. Software does not generally assign each block a permanent numbered SM.',
'Once resident, the block’s warps are managed by SM scheduling machinery. Device-level dispatch and warp instruction scheduling are different stages.',
'This is a logical function, not a reverse-engineered map of the hardware dispatcher.',['cuda']],
['media','gpu','io','Video and JPEG decoders','Seven NVDEC · seven JPEG engines',
'Decoding compressed video and images is a different operation from multiplying matrices. Dedicated decode engines can help feed visual workloads without asking the general arithmetic lanes to perform every decoding step. They are relevant to an AI pipeline even when a language-only workload never uses them.',
'After decoding, data can still require preprocessing and transfer into the format consumed by a model.',
'The diagram groups the published decoder resources. It does not imply an H100 is a gaming GPU or has a matching set of video encoders.',['specs']],
['security','gpu','control','Security and management','Boot, firmware, attestation',
'Confidential-computing support includes a chain of trust, protected execution paths, and evidence about the GPU’s security state. Attestation allows a verifier to check that evidence before trusting a workload with secrets. Firmware and management processors help establish and operate this environment.',
'Security depends on the host, driver, firmware, configuration, and verification policy as well as the GPU. Buying an H100 does not automatically make a running application confidential.',
'This tile groups security and management functions. Feature availability and compatibility must be checked for the specific deployment.',['security']],
['ecc','gpu','control','Memory reliability','ECC and row remapping',
'Error-correcting codes detect or correct specified classes of memory errors. Row remapping can replace problematic memory rows with spare resources. Neither is a promise that every possible hardware or software fault will be corrected. Uncorrectable errors still need reporting and recovery.',
'Long training runs depend on reliability as well as speed. An incorrect value silently propagated through a calculation is a very different problem from a slow transfer.',
'Reliability mechanisms are distributed across the memory system. This tile is a conceptual callout, not one standalone ECC chip on the die.',['ecc']],
['scheduler','sm','control','Warp schedulers','Four SM partitions',
'A warp contains 32 threads. A scheduler chooses an eligible warp instruction to issue; switching to other ready work helps hide waits. Dependencies, unavailable operands, barriers, and execution resources can all prevent a warp from issuing. Many resident warps are useful only if some have useful work ready.',
'Branches can make threads in a warp follow different paths. Inactive lanes do not perform useful work on a path they did not take.',
'A warp is a group of software threads, not 32 CPU cores. The four partition outlines are a schematic organization.',['whitepaper','cuda']],
['registers','sm','memory','Register files','65,536 × 32-bit registers per SM',
'Registers hold values used by executing threads: addresses, intermediate results, loop state, and accumulators. They are very close to the arithmetic, but finite. A kernel that needs more registers per thread can reduce the number of simultaneously resident warps.',
'If values spill, the compiler uses local memory. “Local” describes thread ownership; it does not guarantee that the storage sits in a register or even stays on chip.',
'The total register capacity is 256 KiB. Allocation granularity and other resources matter, so dividing capacity by thread count is only a first approximation.',['tuning','practices']],
['fp32','sm','compute','FP32 arithmetic lanes','128 per SM · 16,896 enabled on the GPU',
'These are the units counted as FP32 CUDA cores. They execute general single-precision floating-point arithmetic. A fused multiply-add computes a × b + c with one final rounding and is counted as two floating-point operations in throughput figures.',
'Elementwise operations, parts of normalization, and many non-matrix calculations need ordinary instructions. A Tensor Core peak is not the throughput of every instruction in a program.',
'A CUDA core is an arithmetic lane, not a fully independent CPU-style core with its own operating system thread.',['whitepaper','ptx']],
['fp64','sm','compute','FP64 arithmetic lanes','64 per SM',
'Double precision uses 64-bit floating-point values and supports more precision than FP32. Many scientific calculations depend on this numerical behavior. H100 has dedicated FP64 arithmetic capacity as well as FP64 matrix operations on Tensor Cores.',
'Choose precision based on error tolerance and numerical stability. Smaller representations can improve throughput, but changing the representation can change the answer.',
'The FP64 Tensor Core peak and ordinary FP64 peak describe different operations; they are not interchangeable benchmarks.',['whitepaper']],
['int32','sm','compute','Integer arithmetic lanes','64 per SM',
'Integer work includes addresses, indexing, counters, masks, and operations on integer data. It is part of the machinery of a matrix kernel even when the model’s values are floating point. The GPU must locate data and coordinate its work as well as calculate on that data.',
'Reducing address-generation overhead can matter when useful arithmetic is small or data movement is complex.',
'INT8 Tensor Core throughput does not describe INT32 lane throughput. The datatype and instruction both matter.',['whitepaper']],
['tensor','sm','compute','Fourth-generation Tensor Cores','Four per SM · 528 enabled in total',
'Tensor Cores execute matrix multiply-accumulate operations on supported tile shapes and numeric formats. Many scalar products are combined into one structured operation. The benefit comes when software lays out and supplies data so these units can keep working.',
'For C = A × B, each result is a sum of products. Inputs can use a smaller format while accumulation uses a wider one, depending on the instruction. Register and shared-memory layouts are part of making this work.',
'FP8, FP16, BF16, TF32, FP64, and INT8 have different capabilities and rates. There is no single meaningful “H100 FLOPS” number without the format and operation.',['whitepaper','cutlass']],
['l1','sm','memory','L1 / shared / texture storage','256 KB combined capacity',
'L1 caches data automatically; shared memory is explicitly used by cooperating threads. On Hopper these functions draw from a combined on-chip storage resource. Allocating more shared memory changes the space available to caching. They are not two independent full-size pools.',
'A block can stage a tile in shared memory and reuse it repeatedly. That reuse can save much more time than simply increasing arithmetic throughput.',
'Up to 228 KB is available as shared memory per SM, with up to 227 KB per block. Larger dynamic allocations require the appropriate opt-in.',['tuning']],
['lsu','sm','io','Load/store units','Connect instructions to memory',
'Loads bring values into the execution path; stores write results out. The load/store machinery handles these instructions and their addresses. Nearby accesses by threads can be combined into fewer transactions, while scattered accesses can move many more bytes than the program actually uses.',
'Shared-memory accesses have their own bank structure. A pattern that looks parallel in source code may serialize when it creates bank conflicts.',
'The tile shows a functional group. The model is not a cycle-accurate memory simulator.',['practices']],
['sfu','sm','compute','Special-function units','Selected mathematical operations',
'Specialized instructions support operations such as approximate reciprocal and transcendental functions. A high-level function call may require several instructions, range handling, and corrections. Its cost and accuracy depend on the implementation and compiler options.',
'Exponentials in softmax are one reason a transformer is more than a sequence of matrix multiplications.',
'Do not assume every sine, exponential, or square-root call maps to one instruction or has the same precision behavior.',['ptx']],
['tma','sm','io','Tensor Memory Accelerator','Asynchronous tensor transfers',
'TMA moves tensor-shaped regions between global and shared memory, and supports specified transfers within a thread-block cluster. One issuing thread can initiate work that would otherwise require many explicit address and copy instructions. The transfer proceeds while other work can continue.',
'Producer warps can prepare the next tile while consumer warps compute on the current one. A barrier establishes when the incoming data is safe to use.',
'TMA does not create extra HBM bandwidth. It reduces orchestration overhead and enables overlap when the pipeline has independent work.',['tuning','cutlass']],
['barrier','sm','control','Asynchronous barriers','Know when the data is ready',
'An asynchronous instruction returning does not necessarily mean its work has finished. Barriers and completion mechanisms coordinate producers, consumers, and accelerators. They prevent a computation from reading a tile before the transfer has completed or overwriting storage that is still in use.',
'The Hopper matrix example links TMA transfers, shared-memory buffers, and asynchronous matrix instructions into a pipeline.',
'This tile represents synchronization functionality. Correct ordering requires following the relevant instruction and memory-model rules.',['ptx','cutlass']],
['dpx','sm','compute','DPX instructions','Fused dynamic-programming operations',
'Dynamic programming builds solutions from related subproblems. Many recurrences repeatedly add values and choose minima or maxima. Hopper’s DPX instructions accelerate supported combinations of these operations, helping workloads such as sequence alignment.',
'An instruction specialized for a recurrence is a different form of acceleration from the matrix operations used by neural networks.',
'DPX is an instruction family, not an extra bank of independently counted “DPX cores.” This callout shares underlying execution resources.',['dpx','ptx']],
['cluster','sm','control','Thread-block clusters','Cooperation across SMs',
'A cluster groups thread blocks with a co-scheduling guarantee and mechanisms to cooperate across their SMs. Distributed shared memory lets a block access shared memory belonging to other blocks in its cluster. This can avoid some round trips through global memory.',
'The cluster is above an individual block in the programming hierarchy. It does not mean every SM can read every other SM’s shared memory at will.',
'This is a programming and execution relationship, not extra SRAM inside one SM. The portable maximum cluster size is eight blocks; H100 can opt into a nonportable larger size.',['cuda','tuning']],
['transformer','sm','control','Transformer Engine','Hardware support plus software recipes',
'Transformer Engine combines supported low-precision arithmetic with software that manages scaling and format choices. FP8 cannot represent every value that FP16 or BF16 can. Scaling maps a tensor’s values into a useful range; the recipe must manage the loss of precision and overflow or underflow risk.',
'The E4M3 and E5M2 encodings trade significand precision against exponent range. Which tensors use which representation is a numerical decision, not just a storage setting.',
'This is a cross-cutting feature, not a separate processor hiding next to the Tensor Cores. Later Transformer Engine features are not all supported by Hopper.',['fp8','scaling']]
];

sources.memory = ['CUDA: virtual memory and translation', 'https://docs.nvidia.com/cuda/cuda-programming-guide/04-special-topics/unified-memory.html'];
sources.management = ['NVIDIA System Management Interface', 'https://docs.nvidia.com/deploy/nvidia-smi/index.html'];
sources.timeline = ['Nsight Systems user guide', 'https://docs.nvidia.com/nsight-systems/UserGuide/index.html'];
parts.push(
['dram','package','memory','DRAM dies inside HBM','Stacked storage, refreshed over time',
'A DRAM cell represents information using stored charge and an access transistor. Charge leaks, so DRAM needs refresh. HBM stacks many memory dies and connects them vertically. The stack exposes a wide interface to the GPU rather than behaving like a single long chain that every request must traverse.',
'On-chip caches use SRAM instead: storage circuits that retain state while powered without DRAM-style refresh. SRAM trades silicon area for access characteristics that suit nearby working data.',
'The four visible layers are an illustration, not the actual die count of an H100 HBM stack. Memory-cell circuits are explained, not individually modeled.',['packaging']],
['mmu','gpu','control','Address translation and TLBs','From virtual addresses to memory locations',
'Programs use virtual addresses. Memory-management machinery translates them using mappings maintained by the system. Translation lookaside buffers cache these mappings, so every load need not perform a full page-table walk. Missing in a translation cache is distinct from missing in a data cache.',
'A unified address space simplifies programming but does not make host memory and HBM identical in bandwidth or latency. Migration and remote access still involve physical movement.',
'This is a conceptual group. Page sizes, TLB structure, entry counts, and exact placement are not reconstructed here.',['memory']],
['clocks','gpu','power','Clock and power management','Timing, limits, and operating state',
'Clock signals coordinate synchronous circuits. The device’s operating state affects how much work can be issued per second, while voltage and switching activity affect power. Management mechanisms monitor conditions and constrain operation when necessary.',
'A kernel can be limited by power or temperature before it reaches a published peak. A power cap is a limit, not an instruction to consume exactly that amount at every moment.',
'The tile represents distributed clock and management functions, not one physical clock box. No fixed all-workload clock frequency is assumed.',['management']],
['instructions','sm','control','Instruction fetch and caches','Keep the program near the execution units',
'The GPU needs instructions as well as data. Instruction caches retain the encoded program close to the SM’s execution machinery. Fetch and issue are separate from reading the matrix operands. Code size, instruction dependencies, and instruction mix can matter even when the data fits in cache.',
'The compiler turns source into executable instructions. A compact high-level expression can expand into many operations; a library call can launch several specialized kernels.',
'The label groups the instruction path. Cache capacity and detailed front-end geometry are not asserted.',['whitepaper','ptx']]
);
